# Generated by Django 4.2 on 2026-01-18 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.generate_code


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_images', models.ImageField(blank=True, default='user.png', null=True, upload_to='Images_Profile', verbose_name='Cover Image')),
                ('address', models.TextField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('code', models.CharField(default=utils.generate_code.generate_code, max_length=10)),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
